### ISSUE TITLE
The archive is corrupt

### ISSUE THREAD

**Issue by hugohuynh** [barracudanetworks/ArchiveStream-php#1] opened 2013-11-07 07:07 UTC
Dear,

I download the latest version, and run index.php in test folder but I got the error "The archive is corrupt" when open the downloaded archive with WinRar.

Thank you,
Hugo

**Comment by ianvonholt** [comment] 2015-04-10 03:29
I have recently run into the same issue, but only if my archive streams above 670mb in size. 

I have an script that will pull all selected files that a user wants and then streams the file on the fly. Anything under 670mb and the archive is completely fine. Anything over, and the file is corrupt. 

What information would you need to help debug?

**Comment by JohnMaguire** [comment] 2015-04-10 03:37
Was this a tar or a zip?

**Comment by ianvonholt** [comment] 2015-04-10 15:42
It is a zip file. 

Windows will flat out refuse to open the corrupt file. Winrar will open it and show one huge file with an erroneous file size of on a roughly 700mb file. 

![Corrupt Zip Screen](https://s3.amazonaws.com/uploads.hipchat.com/82642/596453/vywytBGNod89fbm/upload.png)

Again, as soon as the selected files are under 670mb the file displays  correctly.

![Correct Zip](https://s3.amazonaws.com/uploads.hipchat.com/82642/596273/TRwWEEXJiofn7Bb/upload.png)

Additionally, PHP.ini has some rather high memory limits and execution time for this server. Could this be an issue with Zip64 or gmp settings?

**Comment by JohnMaguire** [comment] 2015-04-10 15:50
Hmm. It's rather odd since we haven't seen this in our environment, and our customers are downloading ZIPs every day. Have you made sure that there's no PHP errors occuring during execution? Is there any chance you might be able to get a broken ZIP to me some way, so that I can analyze it? If you'd like to email me a link to it privately, you can email jmaguire@barracuda.com.

**Comment by ianvonholt** [comment] 2015-04-10 16:54
It is pretty odd. The download setup has been working pretty well for a couple months, however we never really encountered the file size limitations until now. 

There have been no errors generated by PHP within the environment. 

I've e-mailed you a link to a corrupt zip file.

**Comment by JohnMaguire** [comment] 2015-04-10 17:18
I'm seeing that the ZIP is lacking an end-of-central-directory signature. This is created when `finish()` is called on the object after all files have been added. Are you making sure that `finish()` is called at the end of execution?

Also, do you know if this issue affects tar files as well? (You can test by passing anything into the `instance_by_useragent` method that doesn't contain the term "windows".)

**Comment by JohnMaguire** [comment] 2015-04-10 17:20
Err, sorry, please verify that both `complete_file_stream` and `finish` are being called, if you're using the stream methods.

**Comment by ianvonholt** [comment] 2015-04-10 18:47
The archive is indeed failing to complete. 

The call is pretty basic using the ArchiveStream from the example. 
```
$zip = ArchiveStream::instance_by_useragent( 'CPF_WebFTP_Download_' . date('Y_m_d-H:i:s') );

foreach ($pickedFiles as $file) {
    $zip->add_file_from_path($file['internal'], $file['path']);
}

$zip->finish();
```

The add_file_from_path is correctly calling the add_large_file function, initializing the init_file_stream_transfer and dying on a fread call when the archive streams anything above the previously mentioned 670mb. So it seems that a stream_file_part is missed. 

Switching to fgets seems to solve the issue on my current environment. However, this seems like a bad idea due to fgets returning false if it hits a newline.

**Comment by JohnMaguire** [comment] 2015-04-10 18:56
The switch to `fread()` is quite new. Previously we were using `fgets()`, and in production here at Barracuda, we're still using the older version with `fgets()` (I was actually just about to update.)

As such, I'm not surprised there's some unexpected behavior.

While I'm ironing out the issue with `fread()`, there shouldn't be concerns about `fgets()` and newlines. For example:

```shell
jmaguire@ZimsBase [02:41:36] [~/Repositories/cuda/backup] [release/6.0.08 *]
-> % cat > asdf
test
123
jmaguire@ZimsBase [02:55:26] [~/Repositories/cuda/backup] [release/6.0.08 *]
-> % php -a
Interactive shell

php > $fh = fopen('asdf', 'r');
php > while ($data = fgets($fh)) { echo $data; }
test
123
```

**Comment by JohnMaguire** [comment] 2015-04-10 18:58
A little shot in the dark: Is the file you're adding to the ZIP being read from over a socket?

**Comment by ianvonholt** [comment] 2015-04-10 19:11
Nope. 

All the files are local to the code-base. I looked into the possibility of a socket_timeout occurring, for some weird reason, but  there was no indication that this was happening. 

I'll do a bit more testing to see if I can track down what exactly is causing fread to fail, but for me switching back to fgets fixed my problem. 

A bit more about the server: 
CentOS release 6.6 (Final)
PHP 5.4.29 
Apache/2.2.27

**Comment by JohnMaguire** [comment] 2015-04-10 19:27
Interesting. I'll try doing some tests locally using the add from file
call, as we mainly use this library for creating the file on the fly while
streaming from multiple parts. Thanks a lot for the report. :)

**Comment by JohnMaguire** [comment] 2015-04-13 23:43
Interestingly, if I create a ZIP using a 5 bytes file, a 750 MB ASCII file, and a 750 MB binary file, using `fgets` I am getting this:

```
Archive:  possibly_corrupted(3).zip
warning [possibly_corrupted(3).zip]:  zipfile claims to be last disk of a multi-part archive;
  attempting to process anyway, assuming all parts have been concatenated
  together in order.  Expect "errors" and warnings...true multi-part support
  doesn't exist yet (coming soon).
error [possibly_corrupted(3).zip]:  missing 7017068025 bytes in zipfile
  (attempting to process anyway)
error [possibly_corrupted(3).zip]:  attempt to seek before beginning of zipfile
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```

However, switching back to `fread` I am getting this:
```
Archive:  possibly_corrupted(4).zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of possibly_corrupted(4).zip or
        possibly_corrupted(4).zip.zip, and cannot find possibly_corrupted(4).zip.ZIP, period.
```
Pretty weird that I'm getting the error you're getting with `fread`, and you get it with `fgets`. Though I'm still getting an error for `fgets` as well.

**Comment by JohnMaguire** [comment] 2015-04-14 20:23
Can't reproduce using a 5 byte text file, 750MB text file, and 750MB binary file... script below:

```
<?php

// Created for issue: https://github.com/barracudanetworks/ArchiveStream-php/issues/1
// Debugging problem that caused re-open (reported by ianvonholt)

// Just in case
ini_set('max_execution_time', 600);

// Switch to false for a tar file
define('ZIP_FILE', true);

include_once('stream.php');
// Hack to get a zip file even on Linux and vice-versa
if (ZIP_FILE) { $_SERVER['HTTP_USER_AGENT'] = 'windows'; } else { $_SERVER['HTTP_USER_AGENT'] = 'linux'; }

$files = [
	'5B.txt' => 'files/5B.txt',
	'750M.txt' => 'files/500M.txt',
	'750M.bin' => 'files/750M.bin',
];

$zip = ArchiveStream::instance_by_useragent('fread');
foreach ($files as $file => $path)
{
	$zip->add_file_from_path($file, $path);
}

$zip->finish();
```

**Comment by JohnMaguire** [comment] 2015-04-14 20:25
It almost seems like WinRAR isn't respecting the third bit being set in the general purpose flag of the file header (this is what says to ignore the values 0x00 for CRC and 0xFFFF for the length of the data, and to go to the file descriptor for those values.) It's odd that switching back to fgets would fix the problem though.

Just to clarify, is the only difference `fread` -> `fgets`? Or did you checkout an earlier commit that used `fgets`?

**Comment by JohnMaguire** [comment] 2015-05-05 21:06
@ianvonholt I've tried reproducing this in house a few times, and can't seem to do it.

Could you verify that output buffering is turned off? You can do this with the following snippet:

```
while (ob_get_level() > 0) {
    ob_end_clean();
}
```

Many frameworks can turn this on by default.

**Comment by JohnMaguire** [comment] 2015-05-12 16:47
@ianvonholt If you're still interested in trying to get this fixed, please try running the script I provided and letting me know if you get a corrupt ZIP. Otherwise, I'll close this issue as CNR.

**Closed** 2015-08-11 15:52 UTC
